name: nWGS_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.5
  - conda-forge::markdown=3.3.4
  - conda-forge::pymdown-extensions=8.2
  - conda-forge::pygments=2.9.0
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.11 