# Start with an official Python 3.9 image
FROM python:3.9-slim

# Install required packages for git
RUN apt-get update && apt-get install -y git && apt-get clean && rm -rf /var/lib/apt/lists/*

# Clone the sturgeon repository
RUN git clone https://github.com/marcpaga/sturgeon /sturgeon

# Set the working directory
WORKDIR /sturgeon

# Create a virtual environment in the sturgeon directory
RUN python3 -m venv venv

# Activate the virtual environment and install dependencies
# Use a single RUN command to ensure virtual environment activation is preserved
RUN . venv/bin/activate && \
    python3 -m pip install --upgrade pip && \
    pip install . --no-cache-dir
####ps added
RUN apt-get update && apt-get install -y procps
# Set the entry point to use the virtual environment's Python
ENTRYPOINT ["/sturgeon/venv/bin/python3"]
CMD ["--version"]

